import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart'; //Fonts

import 'package:simple_chat/functionality_n_scripts/standalone_methods/general_methods.dart';
import 'package:simple_chat/functionality_n_scripts/configuration_scripts/config_invoke.dart';
import 'package:simple_chat/functionality_n_scripts/standalone_methods/session_methods.dart';
import 'package:simple_chat/screens_pages/landing_page.dart';
import 'package:simple_chat/widgets_and_ui_elements/alert_dialog_builders.dart';
import 'package:simple_chat/functionality_n_scripts/utils/logger_config.dart';

import 'package:simple_chat/cache/chat_titles_list_cache.dart';

class chats_list extends StatefulWidget {
  const chats_list({super.key});

  @override
  State<chats_list> createState() => _chats_listState();
}

class _chats_listState extends State<chats_list> {
  //Control UI behavior
  //bool _button_locked = false;

  //Boolean controller for send button and input controller hint text hiding
  bool _is_processing = false;

  //Manage cache as required
  Future<void> _load_user_chats({bool forceRefresh = false}) async {
    setState(() {
      _is_processing = true;
    });

    //If already cached, no backend call needed
    if (!forceRefresh && ChatTitlesListCache.chat_titles_list_cache != null) {
      log_handler?.i("[chat_page] Chat titles already cached. Skipping backend call.");
      setState(() {
        _is_processing = false;
      });
      return;
    }

    log_handler?.d("[chat_page] Fetching chat titles from backend...");

    final result = await retrieve_all_user_title_chats(context);

    if (result.containsKey("chat_titles")) {
      final titles = List<String>.from(result["chat_titles"]);
      ChatTitlesListCache.chat_titles_list_cache = titles;
    } else {
      ChatTitlesListCache.chat_titles_list_cache = []; //Fallback to empty if error
    }

    setState(() {
      _is_processing = false;
    }); //Trigger rebuild to show new data
  }

  @override
  void initState() {
    super.initState();
    _load_user_chats();
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false, //block system back by default
      onPopInvokedWithResult: (did_pop, result) async {
        if (did_pop) return; //system already popped, nothing to do

        //Navigate to landing page with fade transition
        await Navigator.push(
          context,
          PageRouteBuilder(
            pageBuilder: (context, animation, secondaryAnimation) => const landing_page(),
            transitionsBuilder: (context, animation, secondaryAnimation, child) {
              return FadeTransition(
                opacity: animation,
                child: child,
              );
            },
          ),
        );
      },

      child: Scaffold(
        //Background color
        backgroundColor: config_data.background_color,

        //Top App bar
        appBar: AppBar(
          backgroundColor: config_data.app_bar_color,
          automaticallyImplyLeading: false, //disable autogenerated backtracking icon button

          //auto-generated back button
          actions: [
            IconButton(
              icon: const Icon(Icons.refresh),
              iconSize: 40,
              color: Colors.black,
              onPressed: _is_processing
                  ? null
                  : () async {
                await play_effect_sound(config_data.button_pressed_effect);
                log_handler?.i("[chat_page] Reload icon pressed, refreshing chat titles");
                await _load_user_chats(forceRefresh: true);
              },
            ),
            IconButton(
              icon: const Icon(Icons.close_sharp),
              iconSize: 40,
              color: Colors.black,
              onPressed: _is_processing
                  ? null  //disables the button when true
                  : () async {
                //play sound effect
                await play_effect_sound(config_data.button_pressed_effect);

                //Navigate to landing page with fade transition
                await Navigator.push(
                  context,
                  PageRouteBuilder(
                    pageBuilder: (context, animation, secondaryAnimation) => const landing_page(),
                    transitionsBuilder: (context, animation, secondaryAnimation, child) {
                      return FadeTransition(
                        opacity: animation,
                        child: child,
                      );
                    },
                  ),
                );
              },
            ),
          ],
          title: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisSize: MainAxisSize.min, // Prevents the AppBar from expanding too much
            children: [
              Text(
                "- ${config_data.main_title} -",
                style: GoogleFonts.bebasNeue(
                  textStyle: TextStyle(
                    fontSize: 35,
                    fontWeight: FontWeight.normal,
                    fontStyle: FontStyle.normal,
                    color: config_data.text_color,
                  ),
                ),
              ),
              Text(
                "Google Gemini 2.5 Flash API powered",
                style: TextStyle(
                  fontSize: 9,
                  color: config_data.text_color,
                ),
              ),
            ],
          ),
        ),

        //Actual content
        body: Padding(
          padding: const EdgeInsets.all(15),
          child: Column(
            //Move children to the left
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              //Chat options text
              Text(
                "Chat options",
                style: GoogleFonts.bebasNeue(
                  textStyle: TextStyle(
                    fontSize: 45,
                    fontWeight: FontWeight.normal,
                    fontStyle: FontStyle.normal,
                    color: config_data.text_color,
                  ),
                ),
              ),

              //List of settings
              Expanded(
                child: ListView(
                  children: [
                    //All saved chats section
                    Container(
                      decoration: BoxDecoration(
                        color: config_data.ai_text_box_color,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: config_data.user_text_box_color,
                          width: 2.0,
                        ),
                      ),
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            //Title
                            Text(
                              "All saved chats",
                              style: GoogleFonts.bebasNeue(
                                textStyle: TextStyle(
                                  fontSize: 35,
                                  fontWeight: FontWeight.normal,
                                  fontStyle: FontStyle.normal,
                                  color: config_data.text_color,
                                ),
                              ),
                            ),

                            const SizedBox(height: 10),

                            //Content depending on processing status
                            _is_processing
                                ? const Center(
                                    child: Padding(
                                      padding: EdgeInsets.all(20),
                                      child: CircularProgressIndicator(),
                                    ),
                                  )
                                : (ChatTitlesListCache.chat_titles_list_cache == null ||
                                        ChatTitlesListCache.chat_titles_list_cache!.isEmpty)
                                    ? Padding(
                                        padding: const EdgeInsets.symmetric(vertical: 20),
                                        child: Center(
                                          child: Text(
                                            "No saved chats available.",
                                            style: TextStyle(
                                              color: config_data.text_color,
                                              fontSize: 16,
                                            ),
                                          ),
                                        ),
                                      )
                                    : ListView.builder(
                                        shrinkWrap: true,
                                        physics: const NeverScrollableScrollPhysics(), //prevent scroll conflict
                                        itemCount: ChatTitlesListCache.chat_titles_list_cache!.length,
                                        itemBuilder: (context, index) {
                                          final title = ChatTitlesListCache.chat_titles_list_cache![index];

                                          return Padding(
                                            padding: const EdgeInsets.symmetric(
                                                vertical: 6.0
                                            ),
                                            child: Container(
                                              decoration: BoxDecoration(
                                                color: config_data.background_color,
                                                borderRadius: BorderRadius.circular(10),
                                                border: Border.all(color: Colors.grey.shade700
                                                ),
                                              ),
                                              padding: const EdgeInsets.symmetric(
                                                  horizontal: 12, vertical: 10),
                                              child: Row(
                                                children: [
                                                  // Chat title (left-aligned)
                                                  Expanded(
                                                    child: Text(
                                                      title,
                                                      style: TextStyle(
                                                        color: config_data.text_color,
                                                        fontSize: 18,
                                                      ),
                                                      maxLines: null,
                                                      softWrap: true,
                                                      overflow: TextOverflow.visible,
                                                    ),
                                                  ),

                                                  //Icon buttons
                                                  IconButton(
                                                    icon: const Icon(Icons.refresh),
                                                    color: config_data.user_text_box_color,
                                                    onPressed: _is_processing
                                                        ? null  //disables the button when true
                                                        : () async {
                                                      log_handler?.i("[chat_page] Refresh icon pressed for chat: $title");

                                                      await play_effect_sound(config_data.button_pressed_effect);

                                                      final bool? user_decision = await build_yes_no_alert_dialog(
                                                        context,
                                                        "Accept",
                                                        "Cancel",
                                                        "Load saved chat",
                                                        "Are your certain you wish to load '$title'?, this action "
                                                            "will override whatever conversation you had so far and "
                                                            "if not saved, it will be lost permanently!!!",
                                                      );

                                                      if (user_decision == true) {
                                                        setState(() {
                                                          _is_processing = true;
                                                        });

                                                        log_handler?.d("[chat_page] User proceed with chat retrieval");

                                                        //Call retrieve endpoint
                                                        await retrieve_specific_chat(context, title);

                                                        setState(() {
                                                          _is_processing = false;
                                                        });
                                                      } else {
                                                        log_handler?.d("[chat_page] User cancelled chat retrieval");
                                                      }
                                                    },
                                                  ),
                                                  IconButton(
                                                    icon: const Icon(Icons.delete),
                                                    color: config_data.app_bar_color,
                                                    onPressed: _is_processing
                                                        ? null // disables the button when processing
                                                        : () async {
                                                      log_handler?.i("[chat_page] Delete icon pressed for chat: $title");

                                                      await play_effect_sound(config_data.button_pressed_effect);

                                                      final bool? user_decision = await build_yes_no_alert_dialog(
                                                          context,
                                                          "Accept",
                                                          "Cancel",
                                                          "Delete selected chat",
                                                          "Are your certain you wish to delete '$title'?, this action "
                                                              "will permanently delete the chat and it won't be recoverable "
                                                              "in any way!!!",
                                                      );

                                                      if (user_decision == true) {
                                                        setState(() {
                                                          _is_processing = true;
                                                        });

                                                        log_handler?.d("[chat_page] User proceed with chat deletion");

                                                        //Store original length
                                                        final int original_length = ChatTitlesListCache.chat_titles_list_cache?.length ?? 0;

                                                        //Call delete endpoint
                                                        await delete_specific_chat(context, title);

                                                        //Only refresh if deletion actually happened
                                                        if ((ChatTitlesListCache.chat_titles_list_cache?.length ?? 0) < original_length) {
                                                          setState(() {
                                                            //Triggers UI update
                                                          });
                                                        }

                                                        setState(() {
                                                          _is_processing = false;
                                                        });
                                                      } else {
                                                        log_handler?.d("[chat_page] User cancelled chat deletion");
                                                      }
                                                    },
                                                  ),
                                                ],
                                              ),
                                            ),
                                          );
                                        },
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
