import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart'; //Fonts
import 'package:simple_chat/functionality_n_scripts/session_related/app_storage_class.dart';

import 'package:simple_chat/functionality_n_scripts/standalone_methods/general_methods.dart';
import 'package:simple_chat/functionality_n_scripts/configuration_scripts/config_invoke.dart';
import 'package:simple_chat/functionality_n_scripts/standalone_methods/user_profile_methods.dart';
import 'package:simple_chat/widgets_and_ui_elements/alert_dialog_builders.dart';
import 'package:simple_chat/widgets_and_ui_elements/labeled_text_field.dart';
import 'package:simple_chat/functionality_n_scripts/utils/logger_config.dart';
import 'package:simple_chat/functionality_n_scripts/utils/easter_egg_player.dart';

class settings extends StatefulWidget {
  const settings({super.key});

  @override
  State<settings> createState() => _settingsState();
}

class _settingsState extends State<settings> {
  //Create a TextEditingController for the input box
  final TextEditingController _personality_controller = TextEditingController();
  String _verbose_level_controller = config_data.verbose.toLowerCase();

  final TextEditingController _background_color_controller = TextEditingController();
  final TextEditingController _bar_colors_controller = TextEditingController();
  final TextEditingController _user_textbox_color_controller = TextEditingController();
  final TextEditingController _ai_textbox_color_controller = TextEditingController();

  final TextEditingController _language_controller = TextEditingController();

  final TextEditingController _feedback_controller = TextEditingController();

  bool _sound_effect_controller = config_data.sound_effects_status;
  bool _easter_egg_found_controller = config_data.easter_egg_found;
  bool _button_locked = false;

  //Easter egg
  int _tap_count = 0;
  Timer? _tap_timer;

  //Boolean controller for send button and input controller hint text hiding
  bool _is_processing = false;

  Future<void> _handle_ten_taps_gesture(VoidCallback on_ten_taps) async {
    _tap_count = _tap_count + 1;

    //Reset count if no tap happens within 2 seconds
    _tap_timer?.cancel();
    _tap_timer = Timer(const Duration(seconds: 2), () {
      _tap_count = 0;
    });

    if (_tap_count >= 10) {
      _tap_timer?.cancel();
      _tap_count = 0;
      on_ten_taps(); //Execute the desired action
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      //Background color
      backgroundColor: config_data.background_color,

      //Top App bar
      appBar: AppBar(
        backgroundColor: config_data.app_bar_color,
        automaticallyImplyLeading: false, //disable autogenerated backtracking icon button

        //auto-generated back button
        actions: [
          IconButton(
            icon: const Icon(Icons.close_sharp),
            iconSize: 40,
            color: Colors.black,
            onPressed: _is_processing
                ? null  //disables the button when true
                : () async {
              //play sound effect
              await play_effect_sound(config_data.button_pressed_effect);

              Navigator.pop(context);
            },
          ),
        ],
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize:
              MainAxisSize.min, // Prevents the AppBar from expanding too much
          children: [
            Text(
              "- ${config_data.main_title} -",
              style: GoogleFonts.bebasNeue(
                textStyle: TextStyle(
                  fontSize: 35,
                  fontWeight: FontWeight.normal,
                  fontStyle: FontStyle.normal,
                  color: config_data.text_color,
                ),
              ),
            ),
            Text(
              "Google Gemini 2.0 Flash API powered",
              style: TextStyle(
                fontSize: 9,
                color: config_data.text_color,
              ),
            ),
          ],
        ),
      ),

      //Actual content
      body: Padding(
        padding: const EdgeInsets.all(15),
        child: Column(
          //Move children to the left
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            //Settings text
            Text(
              "Settings",
              style: GoogleFonts.bebasNeue(
                textStyle: TextStyle(
                  fontSize: 45,
                  fontWeight: FontWeight.normal,
                  fontStyle: FontStyle.normal,
                  color: config_data.text_color,
                ),
              ),
            ),

            //List of settings
            Expanded(
              //Listview
              child: ListView(
                children: [
                  //AI section
                  Container(
                    decoration: BoxDecoration(
                      color: config_data.ai_text_box_color, // Background color
                      borderRadius:
                          BorderRadius.circular(12), // Smooth (rounded) edges
                      border: Border.all(
                          color: config_data.user_text_box_color,
                          width: 2.0
                      ),
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                      child: Column(
                        //AI title
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "AI personality",
                            style: GoogleFonts.bebasNeue(
                              textStyle: TextStyle(
                                fontSize: 35,
                                fontWeight: FontWeight.normal,
                                fontStyle: FontStyle.normal,
                                color: config_data.text_color,
                              ),
                            ),
                          ),

                          //Main directory field
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 0, 0, 0),
                            child: LabeledTextField(
                              label: "Personality",
                              controller: _personality_controller,
                              hint_text: "Example: ${config_data.default_directive}",
                              text_color: config_data.text_color,
                              fill_color: config_data.user_text_box_color,
                              hint_color: config_data.suggest_input_color,
                              enabled: !_is_processing,
                              max_length: 150,
                              max_lines: 8,
                              min_lines: 4,
                              height: 180, // adjust height to visually match multiline content
                            ),
                          ),


                          //Verbose level
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 0, 0, 16),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                //Title
                                Text(
                                  "Verbose level",
                                  style: GoogleFonts.roboto(
                                    textStyle: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 18,
                                      color: config_data.text_color,
                                    ),
                                  ),
                                ),
                                //Option buttons
                                Row(
                                  children: [
                                    // Low Button
                                    Expanded(
                                      child: GestureDetector(
                                        onTap: _is_processing
                                            ? null  //disables the button when true
                                            : () async {
                                          if (_button_locked) return; //prevent spam
                                          setState(() {
                                            _button_locked = true; //Lock buttons
                                          });

                                          //play sound effect
                                          await play_effect_sound(config_data.button_pressed_effect);
                                          setState(() {
                                            _verbose_level_controller = "low";
                                            _button_locked = false; //unlock after sound finishes
                                          });
                                          log_handler?.i(
                                              "low button pressed, verbose: $_verbose_level_controller");
                                        },
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(vertical: 12),
                                          decoration: BoxDecoration(
                                            color: _verbose_level_controller == "low"
                                                ? config_data.app_bar_color
                                                : config_data.background_color,
                                            borderRadius: const BorderRadius.only(
                                              topLeft: Radius.circular(10),
                                              bottomLeft: Radius.circular(10),
                                            ),
                                            border: Border.all(
                                              color: Colors.black,
                                              width: 2,
                                            ),
                                          ),
                                          alignment: Alignment.center,
                                          child: Text(
                                            "Low",
                                            style: TextStyle(
                                                color:
                                                    _verbose_level_controller == "low"
                                                        ? Colors.white
                                                        : config_data
                                                            .text_color,
                                                fontWeight:
                                                    _verbose_level_controller == "low"
                                                        ? FontWeight.bold
                                                        : FontWeight.normal),
                                          ),
                                        ),
                                      ),
                                    ),

                                    // Medium Button
                                    Expanded(
                                      child: GestureDetector(
                                        onTap: _is_processing
                                            ? null  //disables the button when true
                                            : () async {
                                          if (_button_locked) return; //prevent spam
                                          setState(() {
                                            _button_locked = true; //Lock buttons
                                          });

                                          //play sound effect
                                          await play_effect_sound(config_data.button_pressed_effect);
                                          setState(() {
                                            _verbose_level_controller = "medium";
                                            _button_locked = false; //unlock after sound finishes
                                          });
                                          log_handler?.i(
                                              "medium button pressed, verbose: $_verbose_level_controller");
                                        },
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(vertical: 12),
                                          decoration: BoxDecoration(
                                            color: _verbose_level_controller == "medium"
                                                ? config_data.app_bar_color
                                                : config_data.background_color,
                                            border: Border.all(
                                              color: Colors.black,
                                              width: 2,
                                            ),
                                          ),
                                          alignment: Alignment.center,
                                          child: Text(
                                            "Medium",
                                            style: TextStyle(
                                                color:
                                                    _verbose_level_controller == "medium"
                                                        ? Colors.white
                                                        : config_data
                                                            .text_color,
                                                fontWeight:
                                                    _verbose_level_controller == "medium"
                                                        ? FontWeight.bold
                                                        : FontWeight.normal),
                                          ),
                                        ),
                                      ),
                                    ),

                                    // High Button
                                    Expanded(
                                      child: GestureDetector(
                                        onTap: _is_processing
                                            ? null  //disables the button when true
                                            : () async {
                                          if (_button_locked) return; //prevent spam
                                          setState(() {
                                            _button_locked = true; //Lock buttons
                                          });

                                          //play sound effect
                                          await play_effect_sound(config_data.button_pressed_effect);
                                          setState(() {
                                            _verbose_level_controller = "high";
                                            _button_locked = false; //unlock after sound finishes
                                          });
                                          log_handler?.i(
                                              "high button pressed, verbose: $_verbose_level_controller");
                                        },
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(
                                              vertical: 12),
                                          decoration: BoxDecoration(
                                            color: _verbose_level_controller == "high"
                                                ? config_data.app_bar_color
                                                : config_data.background_color,
                                            borderRadius: const BorderRadius.only(
                                              topRight: Radius.circular(10),
                                              bottomRight: Radius.circular(10),
                                            ),
                                            border: Border.all(
                                              color: Colors.black,
                                              width: 2,
                                            ),
                                          ),
                                          alignment: Alignment.center,
                                          child: Text(
                                            "High",
                                            style: TextStyle(
                                                color:
                                                    _verbose_level_controller == "high"
                                                        ? Colors.white
                                                        : config_data
                                                            .text_color,
                                                fontWeight:
                                                    _verbose_level_controller == "high"
                                                        ? FontWeight.bold
                                                        : FontWeight.normal),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(
                    width: double.infinity,
                    height: 15,
                  ),

                  //Color section
                  Container(
                    decoration: BoxDecoration(
                      color: config_data.ai_text_box_color, //Background color
                      borderRadius:
                      BorderRadius.circular(12), //Smooth (rounded) edges
                      border: Border.all(
                          color: config_data.user_text_box_color,
                          width: 2.0
                      ),
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                      child: Column(
                        //Colorimetry title
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "Colorimetry",
                            style: GoogleFonts.bebasNeue(
                              textStyle: TextStyle(
                                fontSize: 35,
                                fontWeight: FontWeight.normal,
                                fontStyle: FontStyle.normal,
                                color: config_data.text_color,
                              ),
                            ),
                          ),

                          //Color options
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 0, 0, 6),
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                LabeledTextField(
                                  label: "Background color",
                                  controller: _background_color_controller,
                                  hint_text: "Ivory",
                                  text_color: config_data.text_color,
                                  fill_color: config_data.user_text_box_color,
                                  hint_color: config_data.suggest_input_color,
                                  enabled: !_is_processing, //disable while processing
                                ),
                                const SizedBox(height: 10),
                                LabeledTextField(
                                  label: "Bar colors",
                                  controller: _bar_colors_controller,
                                  hint_text: "Indian Red",
                                  text_color: config_data.text_color,
                                  fill_color: config_data.user_text_box_color,
                                  hint_color: config_data.suggest_input_color,
                                  enabled: !_is_processing, //disable while processing
                                ),
                                const SizedBox(height: 10),
                                LabeledTextField(
                                  label: "Your textbox color",
                                  controller: _user_textbox_color_controller,
                                  hint_text: "Tan",
                                  text_color: config_data.text_color,
                                  fill_color: config_data.user_text_box_color,
                                  hint_color: config_data.suggest_input_color,
                                  enabled: !_is_processing, //disable while processing
                                ),
                                const SizedBox(height: 10),
                                LabeledTextField(
                                  label: "AI textbox color",
                                  controller: _ai_textbox_color_controller,
                                  hint_text: "Light Yellow",
                                  text_color: config_data.text_color,
                                  fill_color: config_data.user_text_box_color,
                                  hint_color: config_data.suggest_input_color,
                                  enabled: !_is_processing, //disable while processing
                                ),
                                const SizedBox(height: 10),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(
                    width: double.infinity,
                    height: 15,
                  ),

                  //AI Language
                  Container(
                    decoration: BoxDecoration(
                      color: config_data.ai_text_box_color, // Background color
                      borderRadius:
                      BorderRadius.circular(12), // Smooth (rounded) edges
                      border: Border.all(
                          color: config_data.user_text_box_color,
                          width: 2.0
                      ),
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                      child: Column(
                        //AI Language title
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "AI Language",
                            style: GoogleFonts.bebasNeue(
                              textStyle: TextStyle(
                                fontSize: 35,
                                fontWeight: FontWeight.normal,
                                fontStyle: FontStyle.normal,
                                color: config_data.text_color,
                              ),
                            ),
                          ),

                          //Language input field
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 0, 0, 16),
                            child: LabeledTextField(
                              label: "Language",
                              controller: _language_controller,
                              hint_text: "Example: ${config_data.default_language}",
                              text_color: config_data.text_color,
                              fill_color: config_data.user_text_box_color,
                              hint_color: config_data.suggest_input_color,
                              enabled: !_is_processing, //disable while processing
                            ),
                          ),

                        ],
                      ),
                    ),
                  ),

                  const SizedBox(
                    width: double.infinity,
                    height: 15,
                  ),

                  //Background image
                  Container(
                    decoration: BoxDecoration(
                      color: config_data.ai_text_box_color, // Background color
                      borderRadius:
                      BorderRadius.circular(12), // Smooth (rounded) edges
                      border: Border.all(
                          color: config_data.user_text_box_color,
                          width: 2.0
                      ),
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                      child: Column(
                        //Background image title
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "Background image",
                            style: GoogleFonts.bebasNeue(
                              textStyle: TextStyle(
                                fontSize: 35,
                                fontWeight: FontWeight.normal,
                                fontStyle: FontStyle.normal,
                                color: config_data.text_color,
                              ),
                            ),
                          ),

                          //Upload image and change background image
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 0, 0, 16),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                SizedBox(
                                  width: double.infinity,
                                  height: 45,
                                  child: GestureDetector(
                                    onTap: _is_processing
                                        ? null  //disables the button when true
                                        : () async {
                                      //play sound effect
                                      await play_effect_sound(config_data.miscellanous_effect);
                                      //TODO: add functionality to change background image
                                      log_handler?.i("Update background image pressed despite big ahh warning");
                                      build_informative_alert_dialog(
                                        context,
                                        "Ok",
                                        "Feature in progress...",
                                        "The feature you just tried to use is in development. Please enjoy"
                                            "all the other features and stay tuned for future updates",
                                      );
                                    },
                                    child: Container(
                                      decoration: BoxDecoration(
                                        color: config_data.background_color,
                                        borderRadius: BorderRadius.circular(16),
                                        border: Border.all(
                                            color: config_data.text_color,
                                            width: 2.0
                                        ),
                                      ),
                                      child: Center(
                                        child: Text(
                                          "-Non-functional yet-",
                                          style: GoogleFonts.bebasNeue(
                                            textStyle: TextStyle(
                                              fontSize: 30,
                                              fontWeight: FontWeight.normal,
                                              fontStyle: FontStyle.normal,
                                              color: config_data.text_color,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(
                    width: double.infinity,
                    height: 15,
                  ),

                  //Sound effects
                  Container(
                    decoration: BoxDecoration(
                      color: config_data.ai_text_box_color, // Background color
                      borderRadius:
                      BorderRadius.circular(12), // Smooth (rounded) edges
                      border: Border.all(
                          color: config_data.user_text_box_color,
                          width: 2.0
                      ),
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                      child: Column(
                        //Sound effects image title
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          //Title
                          Text(
                            "Sound Effects",
                            style: GoogleFonts.bebasNeue(
                              textStyle: TextStyle(
                                fontSize: 35,
                                fontWeight: FontWeight.normal,
                                fontStyle: FontStyle.normal,
                                color: config_data.text_color,
                              ),
                            ),
                          ),

                          //Sound effect switch
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 0, 0, 16),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                //Option buttons
                                Row(
                                  children: [
                                    // On Button
                                    Expanded(
                                      child: GestureDetector(
                                        onTap: _is_processing
                                            ? null  //disables the button when true
                                            : () async {
                                          if (_button_locked) return; //prevent spam
                                          setState(() {
                                            _button_locked = true; //Lock buttons
                                          });

                                          //play sound effect
                                          await play_effect_sound(config_data.button_pressed_effect);
                                          setState(() {
                                            _sound_effect_controller = true;
                                            _button_locked = false; //unlock buttons
                                          });
                                          log_handler?.i(
                                              "sound effects on button pressed, status: $_sound_effect_controller");
                                        },
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(vertical: 12),
                                          decoration: BoxDecoration(
                                            color: _sound_effect_controller == true
                                                ? config_data.app_bar_color
                                                : config_data.background_color,
                                            borderRadius: const BorderRadius.only(
                                              topLeft: Radius.circular(10),
                                              bottomLeft: Radius.circular(10),
                                            ),
                                            border: Border.all(
                                              color: Colors.black,
                                              width: 2,
                                            ),
                                          ),
                                          alignment: Alignment.center,
                                          child: Text(
                                            "On",
                                            style: TextStyle(
                                                color:
                                                _sound_effect_controller == true
                                                    ? Colors.white
                                                    : config_data
                                                    .text_color,
                                                fontWeight:
                                                _sound_effect_controller == true
                                                    ? FontWeight.bold
                                                    : FontWeight.normal),
                                          ),
                                        ),
                                      ),
                                    ),

                                    // Off Button
                                    Expanded(
                                      child: GestureDetector(
                                        onTap: _is_processing
                                            ? null  //disables the button when true
                                            : () async {
                                          if (_button_locked) return; //prevent spam
                                          setState(() {
                                            _button_locked = true; //Lock buttons
                                          });

                                          //play sound effect
                                          await play_effect_sound(config_data.button_pressed_effect);
                                          setState(() {
                                            _sound_effect_controller = false;
                                            _button_locked = false; //unlock buttons
                                          });
                                          log_handler?.i(
                                              "sound effects off button pressed, status: $_sound_effect_controller");
                                        },
                                        child: Container(
                                          padding: const EdgeInsets.symmetric(vertical: 12),
                                          decoration: BoxDecoration(
                                            color: _sound_effect_controller == false
                                                ? config_data.app_bar_color
                                                : config_data.background_color,
                                            borderRadius: const BorderRadius.only(
                                              topRight: Radius.circular(10),
                                              bottomRight: Radius.circular(10),
                                            ),
                                            border: Border.all(
                                              color: Colors.black,
                                              width: 2,
                                            ),
                                          ),
                                          alignment: Alignment.center,
                                          child: Text(
                                            "Off",
                                            style: TextStyle(
                                                color:
                                                _sound_effect_controller == false
                                                    ? Colors.white
                                                    : config_data
                                                    .text_color,
                                                fontWeight:
                                                _sound_effect_controller == false
                                                    ? FontWeight.bold
                                                    : FontWeight.normal),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),

                                const SizedBox(
                                  width: double.infinity,
                                  height: 10,
                                ),

                                if (config_data.easter_egg_found)
                                  EasterEggPlayerInline(
                                    asset_path: 'audio/unfinished.mp3',
                                    text_color: config_data.text_color,
                                  ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(
                    width: double.infinity,
                    height: 15,
                  ),

                  //Feedback
                  Container(
                    decoration: BoxDecoration(
                      color: config_data.ai_text_box_color, // Background color
                      borderRadius:
                      BorderRadius.circular(12), // Smooth (rounded) edges
                      border: Border.all(
                          color: config_data.user_text_box_color,
                          width: 2.0
                      ),
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                      child: Column(
                        //Background image title
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            "Feedback",
                            style: GoogleFonts.bebasNeue(
                              textStyle: TextStyle(
                                fontSize: 35,
                                fontWeight: FontWeight.normal,
                                fontStyle: FontStyle.normal,
                                color: config_data.text_color,
                              ),
                            ),
                          ),

                          //Send feedback
                          Padding(
                            padding: const EdgeInsets.fromLTRB(16, 0, 0, 16),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                //Labeled textfield for feedback
                                LabeledTextField(
                                  label: "Feedback",
                                  controller: _feedback_controller,
                                  hint_text:
                                  "Example: This app is not good, please delete "
                                      "the source code, the repo and Android "
                                      "Studio.",
                                  text_color: config_data.text_color,
                                  fill_color: config_data.user_text_box_color,
                                  hint_color: config_data.suggest_input_color,
                                  enabled: !_is_processing,
                                  max_length: 300,
                                  max_lines: 8,
                                  min_lines: 4,
                                  height: 150, // approximate height for multiline
                                ),

                                SizedBox(
                                  height: 10,
                                ),

                                SizedBox(
                                  width: double.infinity,
                                  height: 45,
                                  child: GestureDetector(
                                    onTap: _is_processing
                                        ? null  //disables the button when true
                                        : () async {
                                      setState(() async {
                                        //Send feedback
                                         await send_feedback_by_email(context,_feedback_controller.text);
                                      });
                                      build_informative_alert_dialog(
                                        context,
                                        "Ok",
                                        "Feedback Sent!!!",
                                        "Your Feedback has been sent through the email/s you selected",
                                      );
                                    },
                                    child: Container(
                                      decoration: BoxDecoration(
                                        color: config_data.background_color,
                                        borderRadius: BorderRadius.circular(16),
                                        border: Border.all(
                                            color: config_data.text_color,
                                            width: 2.0
                                        ),
                                      ),
                                      child: Center(
                                        child: Text(
                                          "Send feedback",
                                          style: GoogleFonts.bebasNeue(
                                            textStyle: TextStyle(
                                              fontSize: 25,
                                              fontWeight: FontWeight.normal,
                                              fontStyle: FontStyle.normal,
                                              color: config_data.text_color,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(
                    width: double.infinity,
                    height: 15,
                  ),

                  //Credits and attributions section
                  GestureDetector(
                    onTap: () async {
                      if (!config_data.easter_egg_found) {
                        await _handle_ten_taps_gesture(() async {
                          setState(() {
                            // Update easter egg found
                            _easter_egg_found_controller = true;
                            update_easter_egg_found(_easter_egg_found_controller);
                            // Reload config_data for runtime changes
                            config_data = app_configuration.fromJson(raw_config_json);

                            log_handler?.i("Easter egg found");
                          });
                          build_informative_alert_dialog(
                            context,
                            "Ok",
                            "You discovered the easter egg!!!",
                            "Congratulations!, either by chance, luck or consciously, you have"
                                "discovered the easter egg in this app, enjoy it in the sound "
                                "effects section after restarting the app",
                          );
                        });
                      } else {
                        log_handler?.d("Easter egg already found");
                      }
                    },

                    child: Container(
                      decoration: BoxDecoration(
                        color: config_data.ai_text_box_color, // Background color
                        borderRadius:
                        BorderRadius.circular(12), // Smooth (rounded) edges
                        border: Border.all(
                            color: config_data.user_text_box_color,
                            width: 2.0
                        ),
                      ),
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(16, 0, 16, 0),
                        child: Column(
                          //AI title
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              "Credits",
                              style: GoogleFonts.bebasNeue(
                                textStyle: TextStyle(
                                  fontSize: 35,
                                  fontWeight: FontWeight.normal,
                                  fontStyle: FontStyle.normal,
                                  color: config_data.text_color,
                                ),
                              ),
                            ),

                            //Credits list
                            Padding(
                              padding: const EdgeInsets.fromLTRB(16, 0, 0, 0),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  //Title
                                  Text(
                                    "- App Icon designed by Freepik",
                                    style: GoogleFonts.roboto(
                                      textStyle: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 18,
                                        color: config_data.text_color,
                                      ),
                                    ),
                                  ),
                                  //Title
                                  Text(
                                    "- Background image designed by violoncelloCH",
                                    style: GoogleFonts.roboto(
                                      textStyle: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 18,
                                        color: config_data.text_color,
                                      ),
                                    ),
                                  ),
                                  Text(
                                    "- App by Rouxxel",
                                    style: GoogleFonts.roboto(
                                      textStyle: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 18,
                                        color: config_data.text_color,
                                      ),
                                    ),
                                  ),
                                  Text(
                                    "- Sound effects by Rouxxel",
                                    style: GoogleFonts.roboto(
                                      textStyle: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 18,
                                        color: config_data.text_color,
                                      ),
                                    ),
                                  ),
                                  if (config_data.easter_egg_found)
                                    Text(
                                      "- Arrangement by Rouxxel",
                                      style: GoogleFonts.roboto(
                                        textStyle: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          fontSize: 18,
                                          color: config_data.text_color,
                                        ),
                                      ),
                                    ),
                                  if (config_data.easter_egg_found)
                                    Text(
                                      "- Original music by Justin Hurwitz, Benj "
                                          "Pasek and Justin Paul",
                                      style: GoogleFonts.roboto(
                                        textStyle: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          fontSize: 18,
                                          color: config_data.text_color,
                                        ),
                                      ),
                                    ),
                                ],
                              ),
                            ),
                            const SizedBox(
                              width: double.infinity,
                              height: 10,
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),

                ],
              ),
            ),
          ],
        ),
      ),

      //Bottom bar
      bottomNavigationBar: BottomAppBar(
        color: config_data.app_bar_color,
        child: Row(
          //Buttons
          children: [
            //Reset Button
            Expanded(
              //Reset button
              child: GestureDetector(
                onTap: _is_processing
                    ? null  //disables the button when true
                    : () async {
                  //play sound effect
                  await play_effect_sound(config_data.button_pressed_effect);

                  //Ask user if they want to reset
                  bool? user_decision = await build_yes_no_alert_dialog(
                    context,
                    "Confirm",
                    "Cancel",
                    "Reset to factory settings",
                    "Are you sure you want to reset all changes to factory settings?, "
                        "this will also modify your saved preferences data like "
                        "AI personality, verbose level among others.",
                  );
                  if (user_decision != true) {
                    log_handler?.i("User cancelled reset.");
                    return;
                  }

                  setState(() async {
                    //Reset to default all changes by user
                    //Reset directive
                    await update_directive(context, config_data.default_directive);

                    //Reset verbose level
                    await update_verbose_level(config_data.default_verbose);

                    //Reset colorimetry
                    await update_color_value("background.color", "mistwhite");
                    await update_color_value("app_bar.color", "deepmagenta");
                    await update_color_value("user_text_boxes.color", "softorchid");
                    await update_color_value("ai_text_boxes.color", "blushpink");

                    //Reset Language
                    await update_user_language(context, config_data.default_language);

                    //Reset sound effect status
                    await update_sound_effect_status(config_data.default_sound_effects_status);

                    //Reload config_data for runtime reset changes
                    config_data = app_configuration.fromJson(raw_config_json);
                    log_handler?.i("Reset button pressed\n"
                        "Reset directory: ${config_data.directive}\n"
                        "Reset verbose: ${config_data.verbose}\n"
                        "Reset Background color: ${config_data.background_color}\n"
                        "Reset Bar colors: ${config_data.app_bar_color}\n"
                        "Reset User textbox color: ${config_data.user_text_box_color}\n"
                        "Reset AI textbox color: ${config_data.ai_text_box_color}\n"
                        "Reset language: ${config_data.user_language}\n"
                        "Reset sound status: ${config_data.sound_effects_status}\n"
                    );

                    //Start reset user preferences request
                    setState(() => _is_processing = true);

                    //Reset preferences to cloud
                    final String? access_token = await AppStorage.get_access_token();
                    final String? user_id = await AppStorage.get_user_id();
                    await save_user_preferences(context,
                      access_token: access_token.toString(),
                      user_id: user_id.toString(),
                      ai_personality: config_data.directive,
                      verbose_level: config_data.verbose,
                      background_color: color_to_hex(config_data.background_color),
                      bar_colors: color_to_hex(config_data.app_bar_color),
                      user_text_box_color: color_to_hex(config_data.user_text_box_color),
                      ai_text_box_color: color_to_hex(config_data.ai_text_box_color),
                      ai_language: config_data.user_language,
                      sound_effects_on: config_data.sound_effects_status,
                    );
                    //play sound effect
                    await play_effect_sound(config_data.miscellanous_effect);
                    build_informative_alert_dialog(
                      context,
                      "Ok",
                      "Changes Reset!!!",
                      "All changes were successfully reset",
                    );
                    setState(() => _is_processing = false);
                  },
                  );
                },
                child: Container(
                  decoration: BoxDecoration(
                    color: config_data.background_color,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(
                      color: Colors.black, //Outline color
                      width: 2.0,          //Outline thickness
                    ),
                  ),
                  child: Center(
                    child: Text(
                      "Reset",
                      style: GoogleFonts.bebasNeue(
                        textStyle: TextStyle(
                          fontSize: 35,
                          fontWeight: FontWeight.normal,
                          fontStyle: FontStyle.normal,
                          color: config_data.text_color,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),

            const SizedBox(
              height: double.infinity,
              width: 10,
            ),

            //Save button
            Expanded(
              //Save button
              child: GestureDetector(
                onTap: _is_processing
                    ? null  //disables the button when true
                    : () async {
                  //play sound effect
                  await play_effect_sound(config_data.button_pressed_effect);

                  //Ask user if they want to save changes
                  bool? user_decision = await build_yes_no_alert_dialog(
                    context,
                    "Confirm",
                    "Cancel",
                    "Save new changes",
                    "Are you sure you want to save the selected changes?, "
                        "this will also modify your saved preferences data on the "
                        "fields you have selected.",
                  );
                  if (user_decision != true) {
                    log_handler?.i("User cancelled saving.");
                    return;
                  }

                  setState(() async {
                      //Only save AI directory if input is not empty
                      if (_personality_controller.text.isNotEmpty &&
                          _personality_controller.text.length >= 20) {
                        await update_directive(
                            context, _personality_controller.text);
                      } else {
                        log_handler?.w(
                            "Skipped updating directive due to invalid input.");
                      }
                      //Save AI verbose level
                      await update_verbose_level(_verbose_level_controller);

                      //Save colorimetry
                      await update_color_value("background.color", _background_color_controller.text);
                      await update_color_value("app_bar.color", _bar_colors_controller.text);
                      await update_color_value("user_text_boxes.color", _user_textbox_color_controller.text);
                      await update_color_value("ai_text_boxes.color", _ai_textbox_color_controller.text);

                      //Only save Language if input is not empty
                      if (_language_controller.text.isNotEmpty &&
                          _language_controller.text.length >= 2) {
                        await update_user_language(
                            context, _language_controller.text);
                      } else {
                        log_handler?.w(
                            "Skipped updating language due to invalid input.");
                      }

                      //Save sound effect status
                      await update_sound_effect_status(_sound_effect_controller);

                      //Reload config_data for runtime changes
                      config_data = app_configuration.fromJson(raw_config_json);
                      log_handler?.i("Save button pressed\n"
                          "Saved directory: ${config_data.directive}\n"
                          "Saved verbose: ${config_data.verbose}\n"
                          "Saved Background color: ${color_to_hex(config_data.background_color)}\n"
                          "Saved Bar colors: ${color_to_hex(config_data.app_bar_color)}\n"
                          "Saved User textbox color: ${color_to_hex(config_data.user_text_box_color)}\n"
                          "Saved AI textbox color: ${color_to_hex(config_data.ai_text_box_color)}\n"
                          "Saved language: ${config_data.user_language}\n"
                          "Saved sound status: ${config_data.sound_effects_status}\n"
                          "Saved easter egg: ${config_data.easter_egg_found}\n"
                      );

                      //Start Save user preferences request
                      setState(() => _is_processing = true);

                      //Save preferences to cloud with reloaded configuration
                      final String? access_token = await AppStorage.get_access_token();
                      final String? user_id = await AppStorage.get_user_id();
                      await save_user_preferences(context,
                        access_token: access_token.toString(),
                        user_id: user_id.toString(),
                        ai_personality: config_data.directive,
                        verbose_level: config_data.verbose,
                        background_color: color_to_hex(config_data.background_color),
                        bar_colors: color_to_hex(config_data.app_bar_color),
                        user_text_box_color: color_to_hex(config_data.user_text_box_color),
                        ai_text_box_color: color_to_hex(config_data.ai_text_box_color),
                        ai_language: config_data.user_language,
                        sound_effects_on: config_data.sound_effects_status,
                      );

                      //play sound effect//
                      await play_effect_sound(config_data.miscellanous_effect);
                      build_informative_alert_dialog(
                        context,
                        "Ok",
                        "Changes saved!!!",
                        "All changes were successfully saved",
                      );
                      setState(() => _is_processing = false);
                    },
                  );
                },
                child: Container(
                  decoration: BoxDecoration(
                    color: config_data.background_color,
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(
                      color: Colors.black, //Outline color
                      width: 2.0,          //Outline thickness
                    ),
                  ),
                  child: Center(
                    child: Text(
                      "Save",
                      style: GoogleFonts.bebasNeue(
                        textStyle: TextStyle(
                          fontSize: 35,
                          fontWeight: FontWeight.normal,
                          fontStyle: FontStyle.normal,
                          color: config_data.text_color,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
